stages:
  - build
  - test  
  - deploy

cache:
  paths:
    - frontend/node_modules/
    - backend/vendor

build:
  stage : build
  script:    
    - cd frontend
    - npm install
    - rm -rf .env.local    
    - cp .env.local.example .env.local      
    - cd .. 
    
test:
  stage: test
  script:
    - cd frontend    
    - cd ..

deploy:
  stage : deploy
  artifacts:
    paths:
      - frontend/dist
  only :
    - master
  script:    
    - cd frontend
    - rm -rf .env.production    
    - cp .env.production.example .env.production  
    - npm run build    
    - cd ..
    - ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "mkdir -p $SSH_PATH/siakad_temp"
    - rsync -arvz -e "ssh -p $SSH_PORT" --progress frontend/dist/ $SSH_USERNAME@$SSH_HOST:$SSH_PATH/siakad_temp    
    - ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "mv $SSH_PATH/siakad $SSH_PATH/siakad_old && mv $SSH_PATH/siakad_temp $SSH_PATH/siakad"
    - ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "rm -rf $SSH_PATH/siakad_old"    
    - rsync -arvz -e "ssh -p $SSH_PORT" --progress backend/app $SSH_USERNAME@$SSH_HOST:$SSH_PATH/api/app
    - rsync -arvz -e "ssh -p $SSH_PORT" --progress backend/database $SSH_USERNAME@$SSH_HOST:$SSH_PATH/api/database
    - rsync -arvz -e "ssh -p $SSH_PORT" --progress backend/routes $SSH_USERNAME@$SSH_HOST:$SSH_PATH/api/routes    
    - rsync -arvz -e "ssh -p $SSH_PORT" --progress backend/.env.production.example $SSH_USERNAME@$SSH_HOST:$SSH_PATH/api/.env.production.example    
